version: "3"

services:
  web:
    build: .
    container_name: epic-api-container-staging
    image: epic-api-image-staging
    ports:
      - "3742:3742"
    env_file:
      - ./env/.env
      - ./env/.development.env
