import { parse } from "flags";
import { isAbsolute, join } from "path";
import { existsSync } from "dfs";
import e from "validator";

import { Input } from "cliffy:prompt";
import { Loader } from "@Core/common/loader.ts";
import { run } from "./lib/run.ts";

export enum PluginSource {
  GIT = "git",
}

export const resolvePluginName = (name: string) =>
  name
    .split("/")
    .filter(Boolean)
    .join("/")
    .split("\\")
    .filter(Boolean)
    .join("\\");

export const addPluginToImportMap = async (
  name: string,
): Promise<{
  imports: Record<string, string>;
  scopes: Record<string, Record<string, string>>;
}> => {
  const ImportMapPath = join(Deno.cwd(), "import_map.json");
  const PluginImportMapPath = join(
    Deno.cwd(),
    "plugins",
    name,
    "import_map.json",
  );
  const RelativePluginPath = `./plugins/${name}/`;

  const ImportMap = (
    await import(`file:///${ImportMapPath}`, {
      with: { type: "json" },
    })
  ).default;

  ImportMap.imports = {
    ...ImportMap.imports,
    [`@Plugins/${name}/`]: RelativePluginPath,
  };

  ImportMap.scopes = {
    ...ImportMap.scopes,
    [RelativePluginPath]: {},
  };

  const PluginImportMap = (
    await import(`file:///${PluginImportMapPath}`, {
      with: { type: "json" },
    })
  ).default;

  const ImportKeys = Object.keys(ImportMap.imports ?? {});
  const PluginImportKeys = Object.keys(PluginImportMap.imports ?? {});

  for (
    const Key of PluginImportKeys.filter(
      (key) => !ImportKeys.includes(key) || /@(-?\w+\/?)+/.test(key),
    )
  ) {
    if (!/^@((Plugin|Core)\/.*|Database)$/.test(Key)) {
      const TempPath = PluginImportMap.imports?.[Key];

      let ResolvedPath = TempPath;

      let IsUrl: boolean;

      try {
        new URL(TempPath);
        IsUrl = true;
      } catch {
        IsUrl = false;
      }

      const IsAbsolute = !IsUrl && isAbsolute(TempPath);
      const IsRelative = !IsUrl && !IsAbsolute;

      if (IsRelative) {
        ResolvedPath = `./${
          join(`./plugins/${name}/`, TempPath).replace(
            /\\/g,
            "/",
          )
        }`;
      }

      ImportMap.scopes[RelativePluginPath][Key] = ResolvedPath;
    }
  }

  await Deno.writeTextFile(
    ImportMapPath,
    JSON.stringify(ImportMap, undefined, 2),
  );

  return ImportMap;
};

export const updatePluginDeclarationFile = async () => {
  const DeclarationFilePath = join(Deno.cwd(), "plugins.d.ts");
  const PluginsName = Loader.getSequence("plugins")?.includes() ?? [];

  let DeclarationFileContent =
    "//! Warning: This is an auto-generated file! Please do not edit this file.";

  for (const PluginName of PluginsName) {
    const RelativePluginDeclarationPath = `./plugins/${PluginName}/index.d.ts`;

    if (existsSync(RelativePluginDeclarationPath)) {
      DeclarationFileContent +=
        `\n/// <reference types="${RelativePluginDeclarationPath}" />`;
    }
  }

  await Deno.writeTextFile(DeclarationFilePath, DeclarationFileContent);

  return DeclarationFileContent;
};

export const addPlugin = async (options: {
  source?: PluginSource;
  name: string | string[];
  branch?: string;
  prompt?: boolean;
}) => {
  try {
    const Options = await e
      .object(
        {
          source: e
            .optional(e.enum(Object.values(PluginSource)))
            .default(PluginSource.GIT),
          name: e
            .optional(e.array(e.string(), { cast: true, splitter: "," }))
            .default(async (ctx) =>
              ctx.parent!.input.prompt
                ? [
                  await Input.prompt({
                    message: "Name of the Plugin",
                  }),
                ]
                : undefined
            ),
          branch: e.optional(e.string()).default(options.branch ?? "main"),
          ignoreIfExists: e.optional(e.boolean()),
        },
        { allowUnexpectedProps: true },
      )
      .validate(options);

    if (Options.name) {
      const PluginsDir = join(Deno.cwd(), "plugins");

      for (const PluginId of Options.name) {
        const [PluginName, Branch] = PluginId.split(":");

        const ResolvedPluginName = resolvePluginName(PluginName);
        const ResolvedBranch = Branch ?? Options.branch;

        const GitRepoUrl = new URL(ResolvedPluginName, "https://github.com");

        // Check if plugin already exists.
        if (Loader.getSequence("plugins")?.includes().has(ResolvedPluginName)) {
          if (Options.ignoreIfExists) continue;

          throw new Error(
            `The plugin '${ResolvedPluginName}' already exists on this project!`,
          );
        }

        const [command, commandOptions] = Options.source === PluginSource.GIT
          ? [
            "git",
            {
              // Add submodule repository from Git.
              args: [
                "submodule",
                "add",
                "-b",
                ResolvedBranch,
                "-f",
                GitRepoUrl.toString(),
                join("plugins", ResolvedPluginName),
              ],
            },
          ]
          : ["unknown", {}];

        const AddPlugin = await run(command, commandOptions);

        if (AddPlugin.success) {
          await Loader.getSequence("plugins")?.add(ResolvedPluginName, {
            source: Options.source,
            branch: ResolvedBranch,
          });

          await addPluginToImportMap(ResolvedPluginName);

          // Delete any useless files and folders
          for (
            const EntryName of [
              ".vscode",
              ".husky",
              "core",
              "docs",
              "env",
              "terraform",
              "database.ts",
              "serve.ts",
              ".lintstagedrc.json",
            ]
          ) {
            await Deno.remove(join(PluginsDir, ResolvedPluginName, EntryName), {
              recursive: true,
            }).catch(() => {
              // Do nothing...
            });
          }

          console.info("Plugin(s) added successfully!");
        } else throw new Error("We were unable to add plugin(s)!");
      }

      await updatePluginDeclarationFile();
    }
  } catch (error) {
    console.error(error, error.issues);
    throw error;
  }
};

if (import.meta.main) {
  const { source, s, name, n } = parse(Deno.args);

  await Loader.load({ includeTypes: ["plugins"], sequenceOnly: true });

  await addPlugin({
    source: source ?? s,
    name: name ?? n,
    prompt: true,
  });

  Deno.exit();
}
